# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sopkathon_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sopkathon_iOS
  pod 'Alamofire', '~> 4.8.2'
  pod 'Kingfisher', '~> 4.10.1'
end
